model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "pragmatic"
plan_mode_reasoning_effort = "xhigh"

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PAT_TOKEN"

[mcp_servers.serena]
startup_timeout_sec = 25
command = "uvx"
args = ["-p", "3.13", "--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--project-from-cwd", "--context", "codex"]

[plugins."github@openai-curated"]
enabled = true
